### ISSUE TITLE
UnicodeDecodeError in spanish calendar

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Dragon-Born/google-api-python-client#113]
```

What steps will reproduce the problem?

1. 
service.events().list(calendarId='5l4gv642tld3dmlbm5vgbv5cm0@group.calendar.goog
le.com').execute()

What is the expected output? What do you see instead?

Event list


Traceback (most recent call last):
  File "<pyshell#25>", line 1, in <module>
    service.events().list(calendarId='5l4gv642tld3dmlbm5vgbv5cm0@group.calendar.google.com').execute()
  File "/usr/local/lib/python2.7/dist-packages/google_api_python_client-1.0beta8-py2.7.egg/apiclient/http.py", line 386, in execute
    headers=self.headers)
  File "/usr/local/lib/python2.7/dist-packages/google_api_python_client-1.0beta8-py2.7.egg/oauth2client/client.py", line 401, in new_request
    redirections, connection_type)
  File "/usr/local/lib/python2.7/dist-packages/httplib2-0.7.4-py2.7.egg/httplib2/__init__.py", line 1544, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/local/lib/python2.7/dist-packages/httplib2-0.7.4-py2.7.egg/httplib2/__init__.py", line 1294, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/local/lib/python2.7/dist-packages/httplib2-0.7.4-py2.7.egg/httplib2/__init__.py", line 1231, in _conn_request
    conn.request(method, request_uri, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 955, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 989, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 951, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 803, in _send_output
    msg = "\r\n".join(self._buffer)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 33: 
ordinal not in range(128)
>>> 


What version of the product are you using? On what operating system?

Ubuntu - Linux
Python2.7
google_api_python_client-1.0beta8


Please provide any additional information below.

The calendar is written in spanish.

```

Original issue reported on code.google.com by `moril...@gmail.com` on 5 Mar 2012 at 8:46

**Comment by GoogleCodeExporter** [comment]
```
The fact that the calendar is in Spanish should not make a difference because 
the error occurs while making the request, before any content is returned. I 
can make that same call and it works for me. Can you try some of the debugging 
tips here to get a better trace of what is going on?

   http://code.google.com/p/google-api-python-client/wiki/Debugging
```

Original comment by `jcgregorio@google.com` on 5 Mar 2012 at 1:45
- Changed state: **Waiting**

**Comment by GoogleCodeExporter** [comment]
```
Closing. Please re-open if this can be reproduced.
```

Original comment by `jcgregorio@google.com` on 2 Apr 2012 at 2:16
- Changed state: **Closed**
