### ISSUE TITLE
Old api used in samples/gtaskqueue_sample/gtaskqueue_puller

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Dragon-Born/google-api-python-client#117]
```
What steps will reproduce the problem?
1. Install gtaskqueue sample
2. Try and lease some tasks
3.

What is the expected output? What do you see instead?

$ gtaskqueue_puller  [options]
Traceback (most recent call last):
  File "gtaskqueue/gtaskqueue/gtaskqueue_puller", line 348, in <module>
    app.run()
  File "/home/stuart/hg/mediawise/curves/Optimiser/worker-ve/lib/python2.7/site-packages/google_apputils-0.1-py2.7.egg/google/apputils/app.py", line 202, in run
    return _actual_start()
  File "/home/stuart/hg/mediawise/curves/Optimiser/worker-ve/lib/python2.7/site-packages/google_apputils-0.1-py2.7.egg/google/apputils/app.py", line 229, in _actual_start
    really_start()
  File "/home/stuart/hg/mediawise/curves/Optimiser/worker-ve/lib/python2.7/site-packages/google_apputils-0.1-py2.7.egg/google/apputils/app.py", line 189, in really_start
    sys.exit(sys.modules['__main__'].main(argv))
  File "gtaskqueue/gtaskqueue/gtaskqueue_puller", line 344, in main
    puller.lease_tasks()
  File "gtaskqueue/gtaskqueue/gtaskqueue_puller", line 312, in lease_tasks
    result = self._get_tasks_from_queue()
  File "gtaskqueue/gtaskqueue/gtaskqueue_puller", line 226, in _get_tasks_from_queue
    body={})
  File "/home/stuart/hg/mediawise/curves/Optimiser/worker-ve/lib/python2.7/site-packages/google_api_python_client-1.0beta8-py2.7.egg/apiclient/discovery.py", line 411, in method
    raise TypeError('Got an unexpected keyword argument "%s"' % name)
TypeError: Got an unexpected keyword argument "body"

What version of the product are you using? On what operating system?
From the hg repsository
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 11.04
Release:    11.04
Codename:   natty


Please provide any additional information below.

Fixed by simply removing the offending line.

```

Original issue reported on code.google.com by `s...@stuartmitchell.com` on 12 Mar 2012 at 12:29

**Comment by GoogleCodeExporter** [comment]
Original comment by `jcgregorio@google.com` on 14 Jun 2012 at 7:38
- Added labels: **taskqueue**

**Comment by GoogleCodeExporter** [comment]
Original comment by `jcgregorio@google.com` on 31 Jul 2012 at 4:19
- Changed state: **Fixed**
