### ISSUE TITLE
Crash problem in google drive desktop application

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Dragon-Born/google-api-python-client#176]
```
What steps will reproduce the problem?
1.Write a desktop application using google drive api
2.Use pyinstaller to output an .exe file
3.When running the program, after user authentication,there is an error 
occurring:
Traceback (most recent call last):
  File "<string>", line 697, in <module>
  File "<string>", line 562, in __init__
  File "build\bdist.win32\egg\oauth2client\tools.py", line 166, in run
  File "build\bdist.win32\egg\oauth2client\client.py", line 1069, in step2_exchange
  File "USB\build\pyi.win32\USB\outPYZ1.pyz/httplib2", line 1544, in request
  File "USB\build\pyi.win32\USB\outPYZ1.pyz/httplib2", line 1294, in _request
  File "USB\build\pyi.win32\USB\outPYZ1.pyz/httplib2", line 1230, in _conn_request
  File "USB\build\pyi.win32\USB\outPYZ1.pyz/httplib2", line 984, in connect
  File "USB\build\pyi.win32\USB\outPYZ1.pyz/httplib2", line 80, in _ssl_wrap_socket
  File "USB\build\pyi.win32\USB\outPYZ1.pyz/ssl", line 381, in wrap_socket
  File "USB\build\pyi.win32\USB\outPYZ1.pyz/ssl", line 141, in __init__
       ssl.SSLError: [Errno 185090050] _ssl.c:340: error:0B084002:x509 certificate rout
       ines:X509_load_cert_crl_file:system lib

What version of the product are you using? 
Google drive api V2
On what operating system?
On Windows XP SP3

```

Original issue reported on code.google.com by `WeichenW...@gmail.com` on 15 Aug 2012 at 1:14

**Comment by GoogleCodeExporter** [comment]
```
Does the application work before using pyinstaller?
```

Original comment by `jcgregorio@google.com` on 15 Aug 2012 at 1:25

**Comment by GoogleCodeExporter** [comment]
```
Yes. So I doubt there is some problem in api and pyinstaller. Just like this 
post:<https://forums.dropbox.com/topic.php?id=65523&replies=1#post-461457>, 
maybe I need to change something.
```

Original comment by `WeichenW...@gmail.com` on 15 Aug 2012 at 1:47

**Comment by GoogleCodeExporter** [comment]
```
Since this looks like an SSL problem, make sure pyinstaller is picking up the 
cacerts.txt file for httplib2:

  http://code.google.com/p/httplib2/source/browse/#hg%2Fpython2%2Fhttplib2
```

Original comment by `jcgregorio@google.com` on 15 Aug 2012 at 2:01

**Comment by GoogleCodeExporter** [comment]
```
I already tried to put cacerts.txt file in the same directory with .exe file 
but it still fails. Is there any other way to enforce pyinstaller use 
cacerts.txt?
```

Original comment by `WeichenW...@gmail.com` on 15 Aug 2012 at 2:05

**Comment by GoogleCodeExporter** [comment]
```
Sorry, I'm not familiar with pyinstaller.

I'm going to mark this as 'invalid' since it doesn't seem to be an issue with 
the google-api-python-client library.
```

Original comment by `jcgregorio@google.com` on 20 Aug 2012 at 1:36
- Changed state: **Invalid**
