### ISSUE TITLE
Getting "Failed to retrieve starting URI" when using python chunked_transfer.py

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Dragon-Born/google-api-python-client#198]
```
I'm getting
Traceback (most recent call last):
  File "chunked_transfer.py", line 212, in <module>
    upload(sys.argv)
  File "chunked_transfer.py", line 144, in upload
    progress, response = request.next_chunk()
  File "/home/konrad/odeks_classification/.env/local/lib/python2.7/site-packages/oauth2client/util.py", line 120, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/konrad/odeks_classification/.env/local/lib/python2.7/site-packages/apiclient/http.py", line 733, in next_chunk
    raise ResumableUploadError("Failed to retrieve starting URI.")
apiclient.errors.ResumableUploadError: Failed to retrieve starting URI.

when using "chunked_transfer.py" example. I'm using newest script version, 
Python 2.7, Ubuntu 11.10

Best,
Konrad
```

Original issue reported on code.google.com by `konrad.k...@10clouds.com` on 25 Sep 2012 at 1:19

**Comment by GoogleCodeExporter** [comment]
```
How are you invoking the sample script? Neglecting to provide a destination 
object name could cause this error.
```

Original comment by `yova...@google.com` on 25 Sep 2012 at 6:22

**Comment by GoogleCodeExporter** [comment]
```
Hi,
Thanks for such quick response! I have missed README note about this JSON API 
being "technical preview". I guess that this could be it since I din't have 
this active :/ Currently I'm waiting for enabling this.. I have checked before 
this destination name and it looked fine, but I will check this again tomorrow.

Thx!
Konrad
```

Original comment by `k.kur...@gmail.com` on 25 Sep 2012 at 6:40

**Comment by GoogleCodeExporter** [comment]
Original comment by `jcgregorio@google.com` on 16 Nov 2012 at 1:41
- Changed state: **Closed**
