### ISSUE TITLE
Error deleting calendar event

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Dragon-Born/google-api-python-client#205]
```
Operating system: Ubuntu server 10.04
Google api-python-client installed with: pip install --upgrade 
google-api-python-client

I creted a simple python script, I can add new events but when I try to delete 
one with this
service.events().delete(calendarId=calID, eventId=eventID).execute()
i have this error:

Traceback (most recent call last):
  File "test.py", line 98, in <module>
    service.events().delete(calendarId=calID, eventId=eventID).execute()
  File "/usr/local/lib/python2.6/dist-packages/oauth2client/util.py", line 120, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.6/dist-packages/apiclient/http.py", line 678, in execute
    raise HttpError(resp, content, uri=self.uri)
apiclient.errors.HttpError: <HttpError 410 when requesting 
https://www.googleapis.com/calendar/v3/calendars/info@---.it/events/lmug5ah6opg6
0u2458bd4ts8j4_20121029T070000Z?key=--- returned "Resource has been deleted">

And the events is not been deleted.


```

Original issue reported on code.google.com by `canellaf...@gmail.com` on 9 Oct 2012 at 8:36

**Comment by GoogleCodeExporter** [comment]
```
I have experienced the same issue with the same python client as above.  For me 
it seems to happen when I try to delete an exception to a recurring event.  I 
believe the following series of actions leads to this error:

* Create a recurring event. This results in recurring event <A>.
* Create an exception <E> for the recurring event <A>.
* Delete the recurring event <A>.

This leaves the exception even though the recurring event was deleted.  Every 
time I try to delete the exception event <E> I get an HTTP 410 error.
```

Original comment by `galen.sa...@gmail.com` on 21 Oct 2012 at 5:10

**Comment by GoogleCodeExporter** [comment]
```
This sounds like an issue with the calendar api itself and not the Python 
client library, and should be raised here:

  https://groups.google.com/forum/embed/?place=forum/google-calendar-api&showsearch=true
```

Original comment by `jcgregorio@google.com` on 23 Oct 2012 at 5:54
- Changed state: **Closed**
