### ISSUE TITLE
Passing a wrong arg name to a method raises TypeError, should be AttributeError

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Dragon-Born/google-api-python-client#23]
```
Passing a wrong arg name to a method raises TypeError, should be AttributeError

```

Original issue reported on code.google.com by `jcgregorio@google.com` on 2 May 2011 at 3:43

**Comment by GoogleCodeExporter** [comment]
```
$ python
Python 2.7.2 (default, Sep 15 2011, 09:58:14) 
[GCC 4.4.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> open(t=12)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Required argument 'name' (pos 1) not found
>>> open('foo.txt', t=12)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 't' is an invalid keyword argument for this function
>>> 

```

Original comment by `jcgregorio@google.com` on 9 Nov 2011 at 7:04
- Changed state: **Invalid**
