### ISSUE TITLE
Bad permissions in oauth2client.egg-info

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Dragon-Born/google-api-python-client#269]
```
cd oauth2client-1.1/oauth2client.egg-info
ls -l 
drwxr-x---  7 schwehr  5000  238 Mar  7 07:38 .
drwxr-x---  9 schwehr  5000  306 Mar  7 07:38 ..
-rw-r-----  1 schwehr  5000  579 Mar  7 07:38 PKG-INFO
-rw-r-----  1 schwehr  5000  584 Mar  7 07:38 SOURCES.txt
-rw-r-----  1 schwehr  5000    1 Mar  7 07:38 dependency_links.txt
-rw-r-----  1 schwehr  5000   27 Mar  7 07:38 requires.txt
-rw-r-----  1 schwehr  5000   13 Mar  7 07:38 top_level.txt

So when oauth2client is installed as a system user, rebuilding packages like 
gflags will fail like this when being built not as the oauth2client user (which 
is usually root).  So this kills the fink build process (that uses an untrusted 
user to build packages) for gflags in oauth2client is installed:

/sw/bin/python2.7 setup.py build
Traceback (most recent call last):
  File "setup.py", line 32, in <module>
    from setuptools import setup
  File "/sw/lib/python2.7/site-packages/setuptools/__init__.py", line 2, in <module>
    from setuptools.extension import Extension, Library
  File "/sw/lib/python2.7/site-packages/setuptools/extension.py", line 5, in <module>
    from setuptools.dist import _get_unpatched
  File "/sw/lib/python2.7/site-packages/setuptools/dist.py", line 6, in <module>
    from setuptools.command.install import install
  File "/sw/lib/python2.7/site-packages/setuptools/command/__init__.py", line 8, in <module>
    from setuptools.command import install_scripts
  File "/sw/lib/python2.7/site-packages/setuptools/command/install_scripts.py", line 3, in <module>
    from pkg_resources import Distribution, PathMetadata, ensure_directory
  File "/sw/lib/python2.7/site-packages/pkg_resources.py", line 2825, in <module>
    add_activation_listener(lambda dist: dist.activate())
  File "/sw/lib/python2.7/site-packages/pkg_resources.py", line 710, in subscribe
    callback(dist)
  File "/sw/lib/python2.7/site-packages/pkg_resources.py", line 2825, in <lambda>
    add_activation_listener(lambda dist: dist.activate())
  File "/sw/lib/python2.7/site-packages/pkg_resources.py", line 2257, in activate
    self.insert_on(path)
  File "/sw/lib/python2.7/site-packages/pkg_resources.py", line 2364, in insert_on
    self.check_version_conflict()
  File "/sw/lib/python2.7/site-packages/pkg_resources.py", line 2403, in check_version_conflict
    for modname in self._get_metadata('top_level.txt'):
  File "/sw/lib/python2.7/site-packages/pkg_resources.py", line 2251, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/sw/lib/python2.7/site-packages/pkg_resources.py", line 1219, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/sw/lib/python2.7/site-packages/pkg_resources.py", line 1211, in get_metadata
    return self._get(self._fn(self.egg_info,name))
  File "/sw/lib/python2.7/site-packages/pkg_resources.py", line 1326, in _get
    stream = open(path, 'rb')
IOError: [Errno 13] Permission denied: 
'/sw/lib/python2.7/site-packages/oauth2client-1.1-py2.7.egg-info/top_level.txt'

ls -l 
/sw/lib/python2.7/site-packages/oauth2client-1.1-py2.7.egg-info/top_level.txt
-rw-r-----  1 root  admin  13 May 15 07:56 
/sw/lib/python2.7/site-packages/oauth2client-1.1-py2.7.egg-info/top_level.txt
```

Original issue reported on code.google.com by `schw...@gmail.com` on 15 May 2013 at 3:02

**Comment by GoogleCodeExporter** [comment]
```
Sorry, I don't understand the problem, can you provide more details?
```

Original comment by `jcgregorio@google.com` on 15 May 2013 at 3:06

**Comment by GoogleCodeExporter** [comment]
Original comment by `jcgregorio@google.com` on 15 May 2013 at 3:06
- Changed state: **Waiting**
