### ISSUE TITLE
None of the adsense samples work

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Dragon-Born/google-api-python-client#271]
```
Trying to run any of the sample scripts inside the 
C:\google-api-python-client\samples\adsense folder, returns, basicly the same 
exception:

Traceback (most recent call last):
  File "C:\google-api-python-client\samples\adsense\get_all_accounts.py", line 5
5, in <module>
    main(sys.argv)
  File "C:\google-api-python-client\samples\adsense\get_all_accounts.py", line 3
5, in main
    service = sample_utils.initialize_service()
  File "C:\google-api-python-client\samples\adsense\sample_utils.py", line 114,
in initialize_service
    credentials = prepare_credentials()
  File "C:\google-api-python-client\samples\adsense\sample_utils.py", line 95, i
n prepare_credentials
    credentials = run(FLOW, storage)
  File "C:\Python27\lib\site-packages\google_api_python_client-1.1-py2.7.egg\oau
th2client\util.py", line 132, in positional_wrapper
    return wrapped(*args, **kwargs)
TypeError: run() takes at least 3 arguments (2 given)

I've used my own client_secrets.json, as downloaded from the api console, and I 
got my adsense API open

Can you help?
```

Original issue reported on code.google.com by `guruy...@gmail.com` on 20 May 2013 at 10:13

**Comment by GoogleCodeExporter** [comment]
```
Please download the samples from:

  https://code.google.com/p/google-api-python-client/downloads/list

The samples are currently in transition as the dependency on the gflags library 
is being removed. All of the samples will be updated by the time the version 
1.2 release is done.

https://groups.google.com/group/google-api-python-client/browse_thread/thread/d9
d4c09dc56feb42#
```

Original comment by `jcgregorio@google.com` on 20 May 2013 at 12:38
- Changed state: **Invalid**
