### ISSUE TITLE
Error on importing simplejson

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Dragon-Born/google-api-python-client#4]
```
What steps will reproduce the problem?

Expected to import without error

{{{
>>> from apiclient.discovery import build
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "./apiclient/discovery.py", line 37, in <module>
    from json import simplejson
ImportError: cannot import name simplejson
}}}

What version of the product are you using? On what operating system?

Hg tip, Python2.6 Lucid

Patch in https://afshar-bugfix.googlecode.com/hg/

```

Original issue reported on code.google.com by `afs...@google.com` on 15 Dec 2010 at 9:23

**Comment by GoogleCodeExporter** [comment]
```
Fixed at tip, thanks!
```

Original comment by `jcgregorio@google.com` on 15 Dec 2010 at 1:47
- Changed state: **Fixed**
