### ISSUE TITLE
missing cacerts.txt file from bundled httplib2

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Dragon-Born/google-api-python-client#58]
```
Trying the sample google-plus-python-starter CLI application, we hit:

timf@linn[387] python plus_cli.py
Traceback (most recent call last):
  File "plus_cli.py", line 114, in <module>
    main()
  File "plus_cli.py", line 73, in main
    serviceUnauth = build_service(None, httpUnauth, settings.API_KEY)
  File "plus_cli.py", line 55, in build_service
    service = apiclient.discovery.build('plus', 'v1', http=http, developerKey=api_key)
  File "/home/timf/projects/feedplus.git/plus-api/usr/lib/python2.6/site-packages/apiclient/discovery.py", line 136, in build
    resp, content = http.request(requested_url)
  File "/home/timf/projects/feedplus.git/plus-api/usr/lib/python2.6/site-packages/httplib2/__init__.py", line 1436, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/home/timf/projects/feedplus.git/plus-api/usr/lib/python2.6/site-packages/httplib2/__init__.py", line 1188, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/home/timf/projects/feedplus.git/plus-api/usr/lib/python2.6/site-packages/httplib2/__init__.py", line 1123, in _conn_request
    conn.connect()
  File "/home/timf/projects/feedplus.git/plus-api/usr/lib/python2.6/site-packages/httplib2/__init__.py", line 890, in connect
    self.disable_ssl_certificate_validation, self.ca_certs)
  File "/home/timf/projects/feedplus.git/plus-api/usr/lib/python2.6/site-packages/httplib2/__init__.py", line 76, in _ssl_wrap_socket
    cert_reqs=cert_reqs, ca_certs=ca_certs)
  File "/usr/lib/python2.6/ssl.py", line 350, in wrap_socket
    suppress_ragged_eofs=suppress_ragged_eofs)
  File "/usr/lib/python2.6/ssl.py", line 113, in __init__
    cert_reqs, ssl_version, ca_certs)
ssl.SSLError: [Errno 185090050] _ssl.c:326: error:0B084002:x509 certificate 
routines:X509_load_cert_crl_file:system lib

trussing the output (I'm using Solaris) we see:

open64("/home/timf/projects/feedplus.git/plus-api/usr/lib/python2.6/site-package
s/httplib2/cacerts.txt", O_RDONLY) Err#2 ENOENT


Once I downloaded a copy of 
http://code.google.com/p/httplib2/source/browse/python2/httplib2/cacerts.txt

and placed it in that directory, I was able to proceed.

This was using google-api-python-client-1.0beta4.zip and 
google-plus-python-starter.zip



```

Original issue reported on code.google.com by `tim...@gmail.com` on 18 Sep 2011 at 10:23

**Comment by GoogleCodeExporter** [comment]
```
Fixed in 
http://code.google.com/p/google-api-python-client/source/detail?r=ca4cb74117c3a3
618f132a42c4f5abd9e3dc10c8
```

Original comment by `jcgregorio@google.com` on 14 Oct 2011 at 7:29
- Changed state: **Fixed**
