### ISSUE TITLE
Buzz sample crashes with less than 2 items in stream

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Dragon-Born/google-api-python-client#59]
```
Retrieved the first two activities
Traceback (most recent call last):
  File "buzz.py", line 126, in <module>
    main(sys.argv)
  File "buzz.py", line 113, in main
    activitylist = activities.list_next(activitylist).execute()
AttributeError: 'NoneType' object has no attribute 'execute'


Fix sample to check for None returned from list_next().
```

Original issue reported on code.google.com by `jcgregorio@google.com` on 19 Sep 2011 at 5:26

**Comment by GoogleCodeExporter** [comment]
Original comment by `jcgregorio@google.com` on 9 Nov 2011 at 8:17
- Changed state: **WontFix**
