### ISSUE TITLE
Error when using APi with google translate

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Dragon-Born/google-api-python-client#6]
```
What steps will reproduce the problem?
1.launch the file main.py in sample/translate/
2.
3.

What is the expected output? What do you see instead?

Normaly the word flower have to be translated.

But I have this error : 

Traceback (most recent call last):
  File "samples/translate/main.py", line 33, in <module>
    main()
  File "samples/translate/main.py", line 29, in main
    q="flower"
  File "/usr/local/lib/python2.6/dist-packages/google_api_python_client-0.1-py2.6.egg/apiclient/discovery.py", line 179, in method
    raise TypeError('Got an unexpected keyword argument "%s"' % name)
TypeError: Got an unexpected keyword argument "q"


What version of the product are you using? On what operating system?
ubuntu 10.10
python 2.6

Please provide any additional information below.



```

Original issue reported on code.google.com by `Mr.Beau....@gmail.com` on 15 Dec 2010 at 3:34

**Comment by GoogleCodeExporter** [comment]
```
This is a known issue and should be fixed with the next push of the stack, at 
that time the client library sample should start working again.
```

Original comment by `jcgregorio@google.com` on 15 Dec 2010 at 6:32
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
Original comment by `jcgregorio@google.com` on 20 Jan 2011 at 3:29
- Changed state: **Fixed**
